---
title: "Hierarchial Cluster Analysis"
author: "Minh Ho"
date: "5/25/2021"
output: html_document
---
```{r}
 # Load the data
data(iris)
iris <- iris[, c(1, 3, 5)]
 # Scaling the data as it must be the same variance/ standard deviation to run clustering of anykind
iris[ ,1] <- scale(iris[, 1])
iris[ ,2] <- scale(iris[, 2])
apply(iris[, c(1, 2)], 2, sd)
```

```{r}
 # Calculate the distance matrix
dist_matrix <- dist(iris[ , c(1, 2)])
hc_complete <- hclust(dist_matrix)
hc_single <- hclust(dist_matrix, method = "single")
hc_average <- hclust(dist_matrix, method = "average")

plot(hc_complete)
plot(hc_single)
plot(hc_average)
```

```{r}
library(ggplot2)
 # simple function
plot_cluster_slice <-  function(df, hc, numclusters) {
  df$clusters <- as.factor(cutree(hc, k = numclusters))
  ggplot(data = df, aes(x = Sepal.Length, y = Petal.Length, color = clusters)) + geom_point()
}

plot_cluster_slice(iris, hc_complete, 2)
plot_cluster_slice(iris, hc_complete, 3)
plot_cluster_slice(iris, hc_complete, 4)
plot_cluster_slice(iris, hc_complete, 5)
```

